CREATE TABLE LISTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE TASKS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    list INT,
    description VARCHAR(500) NOT NULL,
    status INT NOT NULL,
    FOREIGN KEY (list) REFERENCES LISTS(id)
);